// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptuclezzbfszuezuxzgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0dWNsZXp6YmZzenVlenV4emd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTg1NzAsImV4cCI6MjA2Nzg3NDU3MH0.-8S7t4xuQq7VgVXuG4ReFoJwdQYU96nUeWhfnPNAzUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});